### ISSUE TITLE
Unable to compile this extension.

### ISSUE THREAD

**Issue by sitwalkstand** [sferg-msft/vsts-extension-wit-autosave#2]
I have cloned this repo, but I am receiving the following errors when I attempt to 'grunt build':

> $ grunt build
Running "ts:build" (ts) task
Compiling...
Using tsc v2.9.2
node_modules/@types/node/index.d.ts(105,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.
typings/globals/knockout/index.d.ts(6,2): error TS2411: Property 'notifySubscribers' of type '(valueToWrite?: T, event?: string) => void' is not assignable to string index type 'KnockoutBindingHandler'.
typings/globals/knockout/index.d.ts(16,2): error TS2411: Property 'equalityComparer' of type '(a: any, b: any) => boolean' is not assignable to string index type 'KnockoutBindingHandler'.
typings/globals/knockout/index.d.ts(21,5): error TS2411: Property 'indexOf' of type '(searchElement: T, fromIndex?: number) => number' is not assignable to string index type 'KnockoutBindingHandler'.
typings/globals/knockout/index.d.ts(22,5): error TS2411: Property 'slice' of type '(start: number, end?: number) => T[]' is not assignable to string index type 'KnockoutBindingHandler'.
typings/globals/knockout/index.d.ts(23,5): error TS2411: Property 'splice' of type '{ (start: number): T[]; (start: number, deleteCount: number, ...items: T[]): T[]; }' is not assignable to string index type 'KnockoutBindingHandler'.

**Comment by sferg-msft** [comment]
I just updated to the latest sdk and made everything compile again.  Please try again!
